T = {
'+30%（满天赋）': ('+30% (max talents)', '+30 % (talents au max)'),
'0%（新玩家）': ('0% (new player)', '0 % (nouveau joueur)'),
'1 秒没被干扰就回体力': ('Recovers stamina after 1 s undisturbed', 'Récupère de l’endurance après 1 s sans gêne'),
'10% 的对手跑者背着神秘箱，劝退后 GST ×5': ('10% of rival runners carry a Mystery Box: GST ×5 when they quit', '10 % des coureurs rivaux portent une Mystery Box : GST ×5 à l’abandon'),
'120 范围内其他装置出手间隔 −20%': ('Other devices within 120: interval −20%', 'Autres dispositifs à 120 : intervalle −20 %'),
'1× 速度': ('1× speed', 'Vitesse 1×'),
'2× 速度': ('2× speed', 'Vitesse 2×'),
'3 个 Boss 波每局从 6 位传奇跑者里随机抽：Nox（九命复活）、Aurum（召唤金甲跑者）、Slimo（黏液加速）、Rocco（铁头冲刺）、Chuckles（大笑让装置停工）、Datto（对常用装置产生抗性）。':
  ('Each run draws 3 bosses from 6 legendary runners: Nox (nine lives), Aurum (summons golden runners), Slimo (slime boost), Rocco (headstrong dash), Chuckles (laughter jams devices), Datto (adapts to your most-used device).',
   'Chaque partie tire 3 boss parmi 6 coureurs légendaires : Nox (neuf vies), Aurum (invoque des coureurs dorés), Slimo (bave accélérante), Rocco (charge tête baissée), Chuckles (son rire bloque les dispositifs), Datto (s’adapte à ton dispositif favori).'),
'6 种装置：易拉罐投手（单体）、香蕉皮投手（范围滑倒）、洒水器（减速、冻结）、鞋盒无人机（全图空投）、广场舞音响（神曲连锁传播）、宝石发射器（红黄蓝三种宝石）。每种 3 条路线、每条 5 级；主路线可升满，次路线最多 2 级。':
  ('6 devices: Can Thrower (single target), Banana Peeler (area slip), Sprinkler (slow, freeze), Shoebox Drone (map-wide drop), Dance Speaker (chain earworm), Gem Launcher (ruby, topaz, sapphire). Each has 3 paths of 5 tiers; the main path can max out, the secondary stops at tier 2.',
   '6 dispositifs : Lanceur de canettes (cible unique), Lanceur de peaux de banane (glissade de zone), Arroseur (ralentit, gèle), Drone à boîtes (largage sur toute la carte), Enceinte de danse (tube viral en chaîne), Lance-gemmes (rubis, topaze, saphir). Chacun a 3 voies de 5 niveaux ; la voie principale peut être maximisée, la secondaire s’arrête au niveau 2.'),
'Boss 波': ('Boss wave', 'Vague de boss'),
'Boss：{n}（{t}）': ('Boss: {n} ({t})', 'Boss : {n} ({t})'),
'GMT 质押': ('GMT Staking', 'Staking GMT'),
'GST 借贷': ('GST Loan', 'Prêt GST'),
'GST 空投': ('GST Airdrop', 'Airdrop GST'),
'GST 红包': ('GST Red Packet', 'Enveloppe GST'),
'GST 补给': ('GST Supply', 'Ravitaillement GST'),
'Gas Hero 毒气': ('Gas Hero Gas', 'Gaz Gas Hero'),
'Gas Hero 连环毒气': ('Gas Hero Chain Gas', 'Gaz en chaîne Gas Hero'),
'MOOAR 折扣': ('MOOAR Discount', 'Remise MOOAR'),
'Nox 九命': ('Nox: Nine Lives', 'Nox : neuf vies'),
'{n} 名跑者': ('{n} runners', '{n} coureurs'),
'{n} 张': ('{n} cards', '{n} cartes'),
'{n} 级 · {x}': ('Tier {n} · {x}', 'Niv. {n} · {x}'),
'{x} {n} 秒后开始': ('{x} starts in {n} s', '{x} dans {n} s'),
'{x} 退赛！': ('{x} quits!', '{x} abandonne !'),
'{x}徽章': ('{x} Badge', 'Badge {x}'),
'{x}效果 +25%，升级费用 −20%': ('{x}: effect +25%, upgrades −20%', '{x} : effet +25 %, améliorations −20 %'),
'一串香蕉': ('Banana Bunch', 'Régime de bananes'),
'一次扔 2 片，砸 2 个点': ('Throws 2 peels at 2 spots', 'Lance 2 peaux sur 2 points'),
'三连投': ('Triple Toss', 'Triple lancer'),
'下一波': ('Next wave', 'Vague suivante'),
'下一波 Boss：{x}。': ('Next wave boss: {x}.', 'Boss de la prochaine vague : {x}.'),
'主路线': ('Main', 'Principale'),
'九命：第一次退赛会原地复活（40% 体力）': ('Nine Lives: revives once on the spot (40% stamina)', 'Neuf vies : revient une fois sur place (40 % d’endurance)'),
'交易': ('Deal', 'Pacte'),
'人工降雪': ('Snow Machine', 'Canon à neige'),
'今天已跑 ≥ 2 km（热身 +10% 效果）': ('Ran ≥ 2 km today (warm-up +10% effect)', 'Couru ≥ 2 km aujourd’hui (échauffement +10 % d’effet)'),
'传唱': ('Sing-along', 'Refrain'),
'传奇跑者': ('Legendary runner', 'Coureur légendaire'),
'传播': ('Chain', 'Chaîne'),
'传说': ('Legendary', 'Légendaire'),
'低音炮': ('Subwoofer', 'Caisson de basses'),
'体力 +40%': ('Stamina +40%', 'Endurance +40 %'),
'体力低于 25% 的非 Boss 跑者直接退赛': ('Non-boss runners under 25% stamina quit instantly', 'Les coureurs (hors boss) sous 25 % d’endurance abandonnent'),
'先在虚线圆圈里放置装置，再点「开始第 1 波」': ('Place devices in the dashed circles, then press “Start wave 1”', 'Place des dispositifs dans les cercles, puis « Lancer la vague 1 »'),
'光头': ('Bald Dasher', 'Crâne rasé'),
'全图': ('Global', 'Carte'),
'全图空投鞋盒，专砸体力最多的跑者，无视耐力': ('Drops shoeboxes anywhere on the strongest runner, ignores endurance', 'Largue des boîtes partout sur le coureur le plus endurant, ignore l’endurance'),
'全场冻结 2 秒': ('Whole track frozen for 2 s', 'Toute la piste gelée 2 s'),
'全场所有装置效果 +15%': ('All devices +15% effect', 'Tous les dispositifs +15 % d’effet'),
'全城广场舞': ('Citywide Dance', 'Danse dans toute la ville'),
'再多砸 4 名跑者，间隔再 −30%': ('Hits 4 more runners, interval −30%', 'Touche 4 coureurs de plus, intervalle −30 %'),
'再来一局': ('Play again', 'Rejouer'),
'冰桶挑战': ('Ice Bucket Challenge', 'Ice Bucket Challenge'),
'冰水': ('Ice Water', 'Eau glacée'),
'冰河时代': ('Ice Age', 'Ère glaciaire'),
'冰面': ('Black Ice', 'Verglas'),
'冲刺': ('Sprint', 'Sprint'),
'冲线！': ('Crossed!', 'Arrivé !'),
'冻住 1.5 秒，Boss 也吃满减速': ('Freezes 1.5 s; bosses take the full slow', 'Gèle 1,5 s ; les boss subissent tout le ralentissement'),
'冻住非 Boss 跑者 0.8 秒': ('Freezes non-boss runners for 0.8 s', 'Gèle les coureurs (hors boss) 0,8 s'),
'凉水': ('Cold Water', 'Eau froide'),
'减速': ('Slow', 'Ralenti'),
'减速 +10%': ('Slow +10%', 'Ralenti +10 %'),
'出手速度 ×1.6，持续 5 秒': ('Device speed ×1.6 for 5 s', 'Vitesse des dispositifs ×1,6 pendant 5 s'),
'出手速度 ×2，持续 10 秒': ('Device speed ×2 for 10 s', 'Vitesse des dispositifs ×2 pendant 10 s'),
'出手间隔 −15%': ('Interval −15%', 'Intervalle −15 %'),
'出手间隔 −20%': ('Interval −20%', 'Intervalle −20 %'),
'出手间隔 −30%，多传 3 人': ('Interval −30%, chains 3 more', 'Intervalle −30 %, 3 de plus en chaîne'),
'出手间隔 −40%': ('Interval −40%', 'Intervalle −40 %'),
'出手间隔 −60%': ('Interval −60%', 'Intervalle −60 %'),
'出手间隔减半': ('Interval halved', 'Intervalle divisé par 2'),
'分数': ('Score', 'Score'),
'创世鞋': ('Genesis Sneaker', 'Sneaker Genesis'),
'创世鞋盒': ('Genesis Shoebox', 'Boîte Genesis'),
'剩余生命 / 20 × 300': ('Lives left / 20 × 300', 'Vies restantes / 20 × 300'),
'劝退 GST +{n}%': ('GST per runner +{n}%', 'GST par coureur +{n} %'),
'劝退率 × 600': ('Stop rate × 600', 'Taux d’arrêt × 600'),
'加压': ('Pressurize', 'Pression'),
'加料汽水罐': ('Loaded Soda Can', 'Canette chargée'),
'加重鞋盒': ('Heavy Shoebox', 'Boîte lestée'),
'升级半价 ×{n}': ('Half-price upgrades ×{n}', 'Améliorations à moitié prix ×{n}'),
'升级卷轴': ('Level-up Scroll', 'Parchemin d’amélioration'),
'单体速投易拉罐；对耐力跑者只有 25% 效果，「铁罐」2 级后破甲': ('Rapid single-target cans; only 25% vs endurance runners until “Iron Can” tier 2', 'Canettes rapides sur une cible ; 25 % contre les coureurs endurants jusqu’à « Canette en fer » niv. 2'),
'原地复活！': ('Back on her feet!', 'Elle se relève !'),
'双倍铸造': ('Double Mint', 'Double mint'),
'双发香蕉': ('Double Banana', 'Double banane'),
'双声道': ('Stereo', 'Stéréo'),
'双手投': ('Two-handed', 'À deux mains'),
'双桨无人机': ('Twin Rotor', 'Double rotor'),
'变态辣': ('Insanely Hot', 'Ultra piquant'),
'同时放两首': ('Plays two songs at once', 'Joue deux morceaux à la fois'),
'听到的跑者停下来跳 0.25 秒': ('Runners stop to dance for 0.25 s', 'Les coureurs s’arrêtent pour danser 0,25 s'),
'哈': ('Ha', 'Ha'),
'哈哈哈！': ('HAHAHA!', 'HAHAHA !'),
'喷头扩展': ('Wider Nozzle', 'Buse élargie'),
'四脚朝天': ('Flat on Back', 'Les quatre fers en l’air'),
'回收 · +{n} GST': ('Recycle · +{n} GST', 'Recycler · +{n} GST'),
'地动山摇': ('Earthquake Bass', 'Basses sismiques'),
'场上一个装置沿主路线免费升 1 级（没有装置时改为 +100 GST）': ('One device gets a free tier on its main path (+100 GST if you have none)', 'Un dispositif gagne un niveau gratuit sur sa voie principale (+100 GST si aucun)'),
'多传 1 人': ('Chains 1 more', '1 de plus en chaîne'),
'多传 10 人，效果 +6': ('Chains 10 more, effect +6', '10 de plus en chaîne, effet +6'),
'多传 2 人': ('Chains 2 more', '2 de plus en chaîne'),
'多传 3 人，传播不衰减': ('Chains 3 more, no falloff', '3 de plus en chaîne, sans atténuation'),
'夜航': ('Night Flight', 'Vol de nuit'),
'大功率': ('High Wattage', 'Haute puissance'),
'大号鞋盒': ('XL Shoebox', 'Boîte XL'),
'大桶可乐': ('Party Keg', 'Fût de soda'),
'大片香蕉皮': ('Big Peel', 'Grande peau'),
'大香蕉': ('Big Banana', 'Grosse banane'),
'天赋加成': ('Talent bonus', 'Bonus de talents'),
'奖励：30 GST': ('Reward: 30 GST', 'Récompense : 30 GST'),
'奖励：60 GST + 稀有以上': ('Reward: 60 GST + rare or better', 'Récompense : 60 GST + rare ou mieux'),
'宝石': ('Gem', 'Gemme'),
'实心铁罐': ('Solid Iron Can', 'Canette pleine en fer'),
'对 Boss 效果 ×3': ('×3 effect vs bosses', 'Effet ×3 contre les boss'),
'对手体力 +{n}%': ('Rival stamina +{n}%', 'Endurance rivale +{n} %'),
'对手公会的跑者要冲过你的领地。你用「装置」干扰他们，体力耗尽就摔倒退赛。漏过去的跑者会扣你的生命，生命归零即失守。':
  ('Rival guild runners are racing through your territory. Use devices to throw them off; when their stamina runs out they trip and quit. Every runner who gets through costs you a life; at zero lives the territory falls.',
   'Les coureurs d’une guilde rivale traversent ton territoire. Utilise des dispositifs pour les gêner ; à court d’endurance, ils trébuchent et abandonnent. Chaque coureur qui passe te coûte une vie ; à zéro, le territoire tombe.'),
'对手公会的跑者要冲过你的领地。现在只有易拉罐投手，第 3 波开始出现耐力跑者。': ('Rival guild runners are racing through your territory. You start with the Can Thrower; endurance runners appear from wave 3.', 'Des coureurs rivaux traversent ton territoire. Tu commences avec le Lanceur de canettes ; les coureurs endurants arrivent à la vague 3.'),
'对手移速 +{n}%': ('Rival speed +{n}%', 'Vitesse rivale +{n} %'),
'对耐力跑者': ('vs endurance', 'vs endurants'),
'对耐力跑者：25% → 60%': ('vs endurance runners: 25% → 60%', 'Contre les endurants : 25 % → 60 %'),
'对能量盾效果 ×3': ('×3 vs energy shields', 'Effet ×3 contre les boucliers'),
'射程': ('Range', 'Portée'),
'射程 +20': ('Range +20', 'Portée +20'),
'射程 +25': ('Range +25', 'Portée +25'),
'射程 +60，暴击 ×3': ('Range +60, crits ×3', 'Portée +60, critiques ×3'),
'射程内其他装置出手间隔 −25%': ('Other devices in range: interval −25%', 'Autres dispositifs à portée : intervalle −25 %'),
'射程内其他装置效果 +20%': ('Other devices in range: effect +20%', 'Autres dispositifs à portée : effet +20 %'),
'射程内跑者每秒持续受 3 点效果': ('Runners in range take 3 per second', 'Les coureurs à portée subissent 3 par seconde'),
'小音箱': ('Mini Speaker', 'Mini enceinte'),
'小香蕉还会再散开一次': ('Mini bananas split once more', 'Les mini-bananes se divisent encore'),
'已在发展另外两条路线': ('Already developing two other paths', 'Deux autres voies déjà développées'),
'已满级': ('Maxed', 'Au max'),
'已达上限': ('At cap', 'Plafond atteint'),
'已适应：{x}': ('Adapted: {x}', 'Adapté : {x}'),
'幸运宝石': ('Luck Gem', 'Gemme de chance'),
'广场舞女王': ('Dance Floor Queen', 'Reine de la piste'),
'广场舞音响': ('Dance Speaker', 'Enceinte de danse'),
'开始第 1 波': ('Start wave 1', 'Lancer la vague 1'),
'开局：开启起手神秘箱': ('Start: open your first Mystery Box', 'Départ : ouvre ta première Mystery Box'),
'开怀大笑：每 6 秒大笑一次，身边的装置停工 1.5 秒': ('Big Laugh: every 6 s, nearby devices stop for 1.5 s', 'Fou rire : toutes les 6 s, les dispositifs proches s’arrêtent 1,5 s'),
'开箱中': ('Opening box', 'Ouverture'),
'弹跳鞋盒': ('Bouncing Box', 'Boîte rebondissante'),
'当前全局效果：': ('Active effects: ', 'Effets actifs : '),
'当日达': ('Same-day Delivery', 'Livraison le jour même'),
'徽章': ('Badge', 'Badge'),
'快手': ('Quick Hands', 'Mains rapides'),
'快递': ('Express', 'Express'),
'快速喷淋': ('Rapid Spray', 'Arrosage rapide'),
'快速装填': ('Fast Reload', 'Rechargement rapide'),
'慢跑者': ('Jogger', 'Joggeur'),
'所有装置效果 +15%（可叠加）': ('All devices +15% effect (stacks)', 'Tous les dispositifs +15 % d’effet (cumulable)'),
'所有装置每次出手有 20% 概率立刻再来一次': ('Every device has a 20% chance to act again instantly', 'Chaque dispositif a 20 % de chances d’agir à nouveau'),
'所有装置的次路线上限 2 级 → 3 级': ('Secondary path cap 2 → 3 for all devices', 'Plafond de la voie secondaire 2 → 3 pour tous'),
'扔香蕉皮，一片跑者一起滑倒；耐力跑者的克星': ('Throws banana peels that trip a whole group; counters endurance runners', 'Lance des peaux de banane qui font glisser un groupe ; contre les endurants'),
'扩音': ('Amplifier', 'Amplificateur'),
'持续 3 秒，持续效果 +40%': ('Lasts 3 s, +40% over time', 'Dure 3 s, +40 % sur la durée'),
'持续喷淋': ('Steady Spray', 'Arrosage continu'),
'持续效果 ×2.5': ('Effect over time ×2.5', 'Effet sur la durée ×2,5'),
'接下来 3 次路线升级半价': ('Next 3 path upgrades are half price', 'Les 3 prochaines améliorations à moitié prix'),
'提前开波 +{n} GST': ('Early start +{n} GST', 'Départ anticipé +{n} GST'),
'放置和升级费用 −20%': ('Placing and upgrading −20%', 'Placement et améliorations −20 %'),
'放置装置': ('Place a device', 'Placer un dispositif'),
'放置费用 −{n}%': ('Placement cost −{n}%', 'Coût de placement −{n} %'),
'效果': ('Effect', 'Effet'),
'效果 +1': ('Effect +1', 'Effet +1'),
'效果 +1.5': ('Effect +1.5', 'Effet +1,5'),
'效果 +10，出手间隔再 −30%': ('Effect +10, interval −30% more', 'Effet +10, intervalle encore −30 %'),
'效果 +10，射程 +40': ('Effect +10, range +40', 'Effet +10, portée +40'),
'效果 +2': ('Effect +2', 'Effet +2'),
'效果 +20，范围 +25': ('Effect +20, area +25', 'Effet +20, zone +25'),
'效果 +2，对耐力跑者全额生效': ('Effect +2, full effect vs endurance runners', 'Effet +2, plein effet contre les endurants'),
'效果 +3': ('Effect +3', 'Effet +3'),
'效果 +4': ('Effect +4', 'Effet +4'),
'效果 +6': ('Effect +6', 'Effet +6'),
'效果 +8；命中有 10% 概率直接绊倒退赛（非 Boss）': ('Effect +8; 10% chance to trip a non-boss out of the race', 'Effet +8 ; 10 % de chances de faire abandonner (hors boss)'),
'效果 ×2': ('Effect ×2', 'Effet ×2'),
'效果 ×2，对 Boss 不再打折': ('Effect ×2, no penalty vs bosses', 'Effet ×2, sans pénalité contre les boss'),
'效果 ×2，对 Boss 再 ×1.5': ('Effect ×2, another ×1.5 vs bosses', 'Effet ×2, encore ×1,5 contre les boss'),
'效果 ×3': ('Effect ×3', 'Effet ×3'),
'效率宝石': ('Efficiency Gem', 'Gemme d’efficacité'),
'数值没有经过试玩平衡。': ('Numbers are not balanced by playtesting yet.', 'Les valeurs ne sont pas encore équilibrées.'),
'数据分析：每 3 秒对受到最多的装置类型产生 65% 抗性': ('Data Analysis: every 3 s gains 65% resistance to the device hitting him most', 'Analyse de données : toutes les 3 s, résiste à 65 % au dispositif qui le touche le plus'),
'数据控': ('Data Nerd', 'Fan de données'),
'新纪录': ('New record', 'Nouveau record'),
'无人机': ('Drone', 'Drone'),
'无人机群': ('Drone Swarm', 'Essaim de drones'),
'无损音质': ('Lossless Audio', 'Son sans perte'),
'无漏怪波数 / 15 × 100': ('Clean waves / 15 × 100', 'Vagues sans fuite / 15 × 100'),
'无词缀': ('No traits', 'Aucun trait'),
'易拉罐': ('Can', 'Canette'),
'易拉罐投手': ('Can Thrower', 'Lanceur de canettes'),
'普通': ('Common', 'Commun'),
'普通跑者': ('Regular runners', 'Coureurs normaux'),
'暴击率 +10%（可叠加）': ('Crit chance +10% (stacks)', 'Chance de critique +10 % (cumulable)'),
'暴击率 +15%': ('Crit chance +15%', 'Chance de critique +15 %'),
'暴击率 +20%': ('Crit chance +20%', 'Chance de critique +20 %'),
'暴击率 +{n}%': ('Crit chance +{n}%', 'Chance de critique +{n} %'),
'最高分 {n}': ('Best {n}', 'Record {n}'),
'本局构筑': ('This run', 'Cette partie'),
'次路线': ('Secondary', 'Secondaire'),
'次路线上限 3 级': ('Secondary cap 3', 'Plafond secondaire 3'),
'次路线最多 {n} 级': ('Secondary path max tier {n}', 'Voie secondaire : niveau {n} max'),
'每 8 秒冻住全场非 Boss 跑者 2 秒': ('Every 8 s, freezes all non-boss runners for 2 s', 'Toutes les 8 s, gèle tous les coureurs (hors boss) 2 s'),
'每次多砸 2 名跑者': ('Hits 2 more runners each throw', 'Touche 2 coureurs de plus par lancer'),
'每波结束 +100 GST': ('+100 GST after each wave', '+100 GST après chaque vague'),
'每波结束 +40 GST': ('+40 GST after each wave', '+40 GST après chaque vague'),
'每波结束开启神秘箱三选一：宝石、GST 红包、GMT 质押、MOOAR 折扣、Gas Hero 毒气、升级卷轴、创世鞋等。局内 GST 只是关卡内货币，不和任何真实资产挂钩。':
  ('After each wave, open a Mystery Box and pick 1 of 3: gems, GST Red Packets, GMT Staking, MOOAR Discount, Gas Hero Gas, Level-up Scrolls, Genesis Sneakers and more. In-run GST is a level-only currency and is not tied to any real asset.',
   'Après chaque vague, ouvre une Mystery Box et choisis 1 carte sur 3 : gemmes, Enveloppes GST, Staking GMT, Remise MOOAR, Gaz Gas Hero, Parchemins, Sneakers Genesis, etc. Le GST de la partie est une monnaie de niveau, sans lien avec un actif réel.'),
'每波结束获得当前 GST 10% 的利息（最多 60）': ('After each wave, earn 10% interest on your GST (max 60)', 'Après chaque vague, 10 % d’intérêts sur ton GST (max 60)'),
'每第 4 次：砸 Boss 额外扣其 15% 体力，砸其他跑者 ×3': ('Every 4th drop: bosses lose an extra 15% stamina, others take ×3', 'Tous les 4 largages : −15 % d’endurance en plus aux boss, ×3 aux autres'),
'每第 4 首效果 ×3': ('Every 4th song ×3', 'Un morceau sur 4 ×3'),
'毒气范围 +50%、效果翻倍': ('Gas area +50%, effect doubled', 'Zone de gaz +50 %, effet doublé'),
'汽水黏鞋': ('Sticky Soda', 'Soda collant'),
'沾到的跑者辣到跳脚 2 秒': ('Runners hop from the heat for 2 s', 'Les coureurs sautillent de piment 2 s'),
'泡水鞋': ('Soggy Shoes', 'Chaussures trempées'),
'波次': ('Wave', 'Vague'),
'洒水器': ('Sprinkler', 'Arroseur'),
'洒水让跑道湿滑，范围减速': ('Wets the track to slow an area', 'Mouille la piste pour ralentir une zone'),
'洗脑神曲': ('Earworm', 'Tube entêtant'),
'洗脑神曲在跑者之间传播，一次影响好几个': ('An earworm hops between runners, hitting several at once', 'Un tube entêtant passe d’un coureur à l’autre'),
'消防水炮': ('Fire Hose Cannon', 'Lance à incendie'),
'湿滑持续 +1 秒': ('Wet track lasts +1 s', 'Piste mouillée +1 s'),
'湿身': ('Soaked', 'Trempé'),
'滑倒的跑者眩晕 0.6 秒': ('Slipping runners are stunned 0.6 s', 'Les coureurs qui glissent sont sonnés 0,6 s'),
'滑倒范围 +10': ('Slip area +10', 'Zone de glissade +10'),
'火锅底料': ('Hot Pot Base', 'Bouillon fondue chinoise'),
'炸街': ('Street Blaster', 'Sono de rue'),
'点跑道旁的虚线圆圈放置装置，再点已放的装置选择升级路线。每个装置最多发展两条路线：主路线可升满 5 级，次路线最多 2 级。':
  ('Tap a dashed circle beside the track to place a device, then tap it to choose upgrade paths. Each device can develop two paths: the main one up to tier 5, the secondary up to tier 2.',
   'Touche un cercle en pointillé près de la piste pour placer un dispositif, puis touche-le pour choisir ses voies. Chaque dispositif peut développer deux voies : la principale jusqu’au niveau 5, la secondaire jusqu’au niveau 2.'),
'熟透香蕉': ('Overripe Banana', 'Banane trop mûre'),
'燃脂模式所需连续劝退 50 → 30': ('Fat-burn mode needs 30 stops instead of 50', 'Le mode brûle-graisse demande 30 arrêts au lieu de 50'),
'燃脂模式持续 10 秒，出手速度 ×2': ('Fat-burn mode lasts 10 s at ×2 speed', 'Le mode brûle-graisse dure 10 s à vitesse ×2'),
'燃脂模式需连续劝退 {n}': ('Fat-burn at {n} streak', 'Brûle-graisse à {n} d’affilée'),
'燃脂模式！': ('Fat-burn mode!', 'Mode brûle-graisse !'),
'爆破': ('Blast ', 'Piste '),
'爆破跑道': ('Blast Track', 'Piste Explosive'),
'牛市狂奔': ('Bull Run', 'Bull run'),
'王之宝库': ('Royal Treasury', 'Trésor royal'),
'王之宝库：每 4 秒召唤 2 名金甲跑者': ('Royal Treasury: summons 2 golden runners every 4 s', 'Trésor royal : invoque 2 coureurs dorés toutes les 4 s'),
'玩法说明': ('How to play', 'Comment jouer'),
'目标': ('Targets', 'Cibles'),
'盾破': ('Shield down', 'Bouclier brisé'),
'瞄准': ('Aim', 'Visée'),
'神秘箱': ('Mystery Box', 'Mystery Box'),
'神秘箱轰炸': ('Mystery Box Strike', 'Frappe Mystery Box'),
'移速 +40%': ('Speed +40%', 'Vitesse +40 %'),
'稀有': ('Rare', 'Rare'),
'稳': ('Resist', 'Résiste'),
'稳妥': ('Safe', 'Sûr'),
'空中支援': ('Air Support', 'Soutien aérien'),
'空位 · 选一个装置': ('Empty spot · choose a device', 'Emplacement libre · choisis un dispositif'),
'空投支援': ('Airdrop Support', 'Soutien largage'),
'立即开始第 {n} 波 · +{b} GST': ('Start wave {n} now · +{b} GST', 'Lancer la vague {n} · +{b} GST'),
'立即生效：+250 GST；之后对手体力 +15%': ('Instant: +250 GST; rivals get +15% stamina from now on', 'Immédiat : +250 GST ; les rivaux ont ensuite +15 % d’endurance'),
'立即生效：对手移速 +15%；劝退获得 GST +50%': ('Instant: rivals +15% speed; +50% GST per runner stopped', 'Immédiat : rivaux +15 % de vitesse ; +50 % de GST par coureur arrêté'),
'立即生效：所有装置效果 +40%；生命 −10': ('Instant: all devices +40% effect; lives −10', 'Immédiat : tous les dispositifs +40 % d’effet ; vies −10'),
'立即获得 120 GST': ('Get 120 GST now', 'Gagne 120 GST tout de suite'),
'笑声': ('Laughter', 'Fou rire'),
'第 {n} 波': ('Wave {n}', 'Vague {n}'),
'第 {n} 波守住 · +{g} GST': ('Wave {n} held · +{g} GST', 'Vague {n} tenue · +{g} GST'),
'第 {n} 波进行中': ('Wave {n} in progress', 'Vague {n} en cours'),
'第 {r} 局 · 最高分 {b}': ('Run {r} · best {b}', 'Partie {r} · record {b}'),
'第 {r} 局 · 精英波 {e} 次': ('Run {r} · {e} elite waves', 'Partie {r} · {e} vagues d’élite'),
'精准': ('Precision', 'Précision'),
'精英奖励：这次的神秘箱只出稀有和传说。': ('Elite reward: this Mystery Box only holds rare and legendary cards.', 'Bonus d’élite : cette Mystery Box ne contient que du rare et du légendaire.'),
'精英小队': ('Elite squad', 'Escouade d’élite'),
'精英波': ('Elite wave', 'Vague d’élite'),
'终点': ('Finish', 'Arrivée'),
'绊倒退赛': ('Tripped out', 'Trébuche et abandonne'),
'罐头暴雨': ('Can Storm', 'Pluie de canettes'),
'罐头炮': ('Can Cannon', 'Canon à canettes'),
'耐力跑者': ('Endurance runner', 'Coureur endurant'),
'耐力跑者的鞋泡水，3 秒内失去耐力加成': ('Soaks endurance runners’ shoes: no endurance bonus for 3 s', 'Trempe les chaussures des endurants : plus de bonus pendant 3 s'),
'生命': ('Lives', 'Vies'),
'生命 +6': ('Lives +6', 'Vies +6'),
'生命 −{n}': ('Lives −{n}', 'Vies −{n}'),
'能量盾': ('Energy Shield', 'Bouclier d’énergie'),
'能量饮料站': ('Energy Drink Station', 'Stand de boissons énergisantes'),
'自动投罐机': ('Auto Can Launcher', 'Lanceur automatique'),
'舒适宝石': ('Comfort Gem', 'Gemme de confort'),
'范围': ('Area', 'Zone'),
'落地后再弹出 3 根小香蕉': ('Bursts into 3 mini bananas on landing', 'Éclate en 3 mini-bananes à l’impact'),
'落地后溅出 4 块碎皮，各 30% 效果': ('Splatters 4 peel bits on landing, 30% each', 'Projette 4 morceaux de peau à l’impact, 30 % chacun'),
'落点留下 2 秒辣油': ('Leaves chili oil for 2 s', 'Laisse de l’huile pimentée 2 s'),
'蓝牙串联': ('Bluetooth Link', 'Liaison Bluetooth'),
'补水光环': ('Hydration Aura', 'Aura d’hydratation'),
'补水站': ('Water Station', 'Point d’eau'),
'补给': ('Refuel', 'Ravitaillement'),
'补给站站长': ('Aid Station Chief', 'Chef du ravitaillement'),
'被冻住的跑者受到所有效果 +60%': ('Frozen runners take +60% from everything', 'Les coureurs gelés subissent +60 % de tout'),
'被淋湿的跑者受到所有效果 +25%': ('Wet runners take +25% from everything', 'Les coureurs mouillés subissent +25 % de tout'),
'被砸中的跑者鞋底发黏，2 秒内受到所有效果 +20%': ('Hit runners get sticky soles: +20% from everything for 2 s', 'Semelles collantes : +20 % de tout pendant 2 s'),
'装置': ('Device', 'Dispositif'),
'装置效果 {s}{n}%': ('Device effect {s}{n}%', 'Effet des dispositifs {s}{n} %'),
'解锁广场舞音响：洗脑神曲在跑者之间传播': ('Unlock Dance Speaker: an earworm hops between runners', 'Débloque l’Enceinte de danse : un tube passe de coureur en coureur'),
'解锁洒水器：跑道湿滑，范围减速': ('Unlock Sprinkler: wet track, area slow', 'Débloque l’Arroseur : piste glissante, ralentit une zone'),
'解锁鞋盒无人机：全图空投鞋盒，无视耐力': ('Unlock Shoebox Drone: map-wide drops, ignores endurance', 'Débloque le Drone à boîtes : largages partout, ignore l’endurance'),
'解锁香蕉皮投手：一片跑者一起滑倒，专克耐力跑者': ('Unlock Banana Peeler: trips whole groups, counters endurance runners', 'Débloque le Lanceur de peaux : fait glisser des groupes, contre les endurants'),
'起点': ('Start', 'Départ'),
'跑团': ('Running Club', 'Club de course'),
'跑者退赛时喷出毒气，波及身边跑者，可以连锁': ('Runners who quit release gas that hits those nearby, and can chain', 'Les coureurs qui abandonnent libèrent un gaz qui touche les voisins, en chaîne'),
'跑道': ('Track', 'Explosive'),
'跟着跳': ('Dance Along', 'Danse avec moi'),
'辣到退赛的跑者会把辣油溅到身边': ('Runners who quit from the heat splash chili oil around', 'Les coureurs qui abandonnent éclaboussent d’huile pimentée'),
'辣椒油': ('Chili Oil', 'Huile pimentée'),
'辣椒粉': ('Chili Powder', 'Piment en poudre'),
'辣油泼地': ('Oil Slick', 'Flaque pimentée'),
'还没有卡': ('No cards yet', 'Aucune carte'),
'远投': ('Long Toss', 'Lancer long'),
'远程狙罐': ('Sniper Can', 'Canette de précision'),
'连投': ('Rapid Toss', 'Lancers rapides'),
'连续劝退 ×{n}': ('Streak ×{n}', 'Série ×{n}'),
'连续打卡': ('Check-in Streak', 'Série de check-ins'),
'退赛时 2 名跟跑者接力': ('2 pacers take over when one quits', '2 meneurs prennent le relais à l’abandon'),
'退赛通知': ('DNF notice', 'Avis d’abandon'),
'选好后有 8 秒布置时间。': ('You get 8 seconds to set up after choosing.', 'Tu as 8 secondes pour te préparer.'),
'选择第 {n} 段跑道': ('Choose stretch {n}', 'Choisis le tronçon {n}'),
'透支生命': ('Overdraw Lives', 'Vies à découvert'),
'通关': ('Territory held!', 'Territoire défendu !'),
'道具': ('Item', 'Objet'),
'重低音': ('Heavy Bass', 'Basses lourdes'),
'重低音效果 ×8': ('Heavy bass hits ×8', 'Basses lourdes ×8'),
'重型鞋盒': ('Heavy Box', 'Boîte lourde'),
'重抽 · {n} GST': ('Reroll · {n} GST', 'Relancer · {n} GST'),
'金王': ('Golden King', 'Roi doré'),
'铁头冲刺': ('Headstrong Dash', 'Charge tête baissée'),
'铁头冲刺：每 5 秒冲刺 1 秒，3 倍速': ('Headstrong Dash: every 5 s, sprints at ×3 speed for 1 s', 'Charge tête baissée : toutes les 5 s, sprint ×3 pendant 1 s'),
'铁皮罐': ('Tin Can', 'Canette en tôle'),
'铁罐': ('Iron Can', 'Canette en fer'),
'锁定': ('Locked', 'Verrouillé'),
'间隔': ('Interval', 'Intervalle'),
'震地': ('Ground Shake', 'Secousse'),
'震碎能量盾': ('Shield Shatter', 'Brise-bouclier'),
'鞋匠': ('Cobbler', 'Cordonnier'),
'鞋匠 → {c}': ('Cobbler → {c}', 'Cordonnier → {c}'),
'鞋盒弹跳再砸 2 名跑者，50% 效果': ('Box bounces to 2 more runners at 50%', 'La boîte rebondit sur 2 coureurs de plus à 50 %'),
'鞋盒无人机': ('Shoebox Drone', 'Drone à boîtes'),
'鞋盒落地震晕 0.4 秒': ('Box impact stuns for 0.4 s', 'L’impact sonne 0,4 s'),
'音乐 关': ('Music off', 'Musique off'),
'音乐 开': ('Music on', 'Musique on'),
'音响': ('Speaker', 'Enceinte'),
'音效 关': ('Sound off', 'Son off'),
'音效 开': ('Sound on', 'Son on'),
'领地失守 · 第 {n} 波': ('Territory lost · wave {n}', 'Territoire perdu · vague {n}'),
'领地跑道，点击虚线圆圈放置装置': ('Territory track; tap a dashed circle to place a device', 'Piste du territoire ; touche un cercle pour placer un dispositif'),
'额外 35% 能量护盾': ('Extra 35% energy shield', 'Bouclier d’énergie +35 %'),
'香蕉海啸': ('Banana Tsunami', 'Tsunami de bananes'),
'香蕉皮': ('Banana', 'Banane'),
'香蕉皮投手': ('Banana Peeler', 'Lanceur de peaux de banane'),
'香蕉碎片': ('Peel Shrapnel', 'Éclats de peau'),
'香蕉船': ('Banana Split', 'Banana split'),
'香蕉连环': ('Banana Cascade', 'Cascade de bananes'),
'香蕉雨': ('Banana Rain', 'Pluie de bananes'),
'马拉松模式': ('Marathon Mode', 'Mode marathon'),
'高压水枪': ('Pressure Washer', 'Nettoyeur haute pression'),
'高压水柱': ('Water Jet', 'Jet d’eau'),
'高风险': ('Risky', 'Risqué'),
'魔性旋律': ('Catchy Loop', 'Mélodie obsédante'),
'魔鬼椒': ('Ghost Pepper', 'Piment fantôme'),
'黏液国王': ('Slime King', 'Roi visqueux'),
'黏液王冠：身后留下黏液，踩到的跑者加速 30% 并回体力': ('Slime Crown: leaves a slime trail; runners on it get +30% speed and recover stamina', 'Couronne visqueuse : laisse une traînée ; les coureurs dessus gagnent +30 % de vitesse et récupèrent'),
'黑猫': ('Black Cat', 'Chat noir'),
'（选后可在空位放置）': (' (place it on an empty spot)', ' (à placer sur un emplacement libre)'),
'，下一级「{x}」不可用': ('; next tier “{x}” unavailable', ' ; niveau suivant « {x} » indisponible'),
}
T.update({
'出手速度 ×{r}，持续 {n} 秒': ('Device speed ×{r} for {n} s', 'Vitesse des dispositifs ×{r} pendant {n} s'),
'全场冻结 {n} 秒': ('Whole track frozen for {n} s', 'Toute la piste gelée {n} s'),
'{n} 条提示': ('{n} notes', '{n} remarques'),
'读取表格的组件加载失败，请检查网络后重试': ('Could not load the spreadsheet reader. Check your connection and try again.', 'Impossible de charger le lecteur de tableur. Vérifie ta connexion et réessaie.'),
'缺少工作表「{x}」，使用默认值': ('Sheet “{x}” is missing; using defaults', 'Feuille « {x} » absente ; valeurs par défaut utilisées'),
'{w}：「{v}」不是数字，使用默认值 {d}': ('{w}: “{v}” is not a number; using default {d}', '{w} : « {v} » n’est pas un nombre ; valeur par défaut {d}'),
'全局 {x}': ('Global {x}', 'Global {x}'),
'全局：未知参数「{x}」已忽略': ('Global: unknown setting “{x}” ignored', 'Global : paramètre inconnu « {x} » ignoré'),
'装置第 {n} 行：未知 id「{x}」已忽略': ('Devices row {n}: unknown id “{x}” ignored', 'Dispositifs ligne {n} : id inconnu « {x} » ignoré'),
'装置 {x} {k}': ('Device {x} {k}', 'Dispositif {x} {k}'),
'升级路线第 {n} 行：找不到对应路线': ('Paths row {n}: no matching path', 'Voies ligne {n} : voie introuvable'),
'升级第 {n} 行：找不到对应等级': ('Upgrades row {n}: no matching tier', 'Améliorations ligne {n} : niveau introuvable'),
'升级第 {n} 行 cost': ('Upgrades row {n} cost', 'Améliorations ligne {n} cost'),
'升级第 {n} 行：效果「{x}」写法有误，保留原效果': ('Upgrades row {n}: effect “{x}” is invalid; kept the previous effect', 'Améliorations ligne {n} : effet « {x} » invalide ; effet précédent conservé'),
'敌人第 {n} 行：未知 id 已忽略': ('Enemies row {n}: unknown id ignored', 'Ennemis ligne {n} : id inconnu ignoré'),
'敌人 {x} {k}': ('Enemy {x} {k}', 'Ennemi {x} {k}'),
'波次第 {n} 行 {k}': ('Waves row {n} {k}', 'Vagues ligne {n} {k}'),
'Boss 第 {n} 行：未知 id 已忽略': ('Bosses row {n}: unknown id ignored', 'Boss ligne {n} : id inconnu ignoré'),
'Boss {x} enabled': ('Boss {x} enabled', 'Boss {x} enabled'),
'Boss {x} p{i}': ('Boss {x} p{i}', 'Boss {x} p{i}'),
'卡牌第 {n} 行：未知 id「{x}」已忽略': ('Cards row {n}: unknown id “{x}” ignored', 'Cartes ligne {n} : id inconnu « {x} » ignoré'),
'卡牌 {x} enabled': ('Card {x} enabled', 'Carte {x} enabled'),
'卡牌 {x} stack': ('Card {x} stack', 'Carte {x} stack'),
'卡牌 {x} v1': ('Card {x} v1', 'Carte {x} v1'),
'卡牌 {x} v2': ('Card {x} v2', 'Carte {x} v2'),
'地图第 {n} 行 x': ('Map row {n} x', 'Carte ligne {n} x'),
'地图第 {n} 行 y': ('Map row {n} y', 'Carte ligne {n} y'),
'地图：跑道至少需要 2 个点，使用默认跑道': ('Map: the track needs at least 2 points; using the default track', 'Carte : la piste demande au moins 2 points ; piste par défaut'),
'地图：至少需要 1 个空位，使用默认空位': ('Map: at least 1 spot is needed; using default spots', 'Carte : il faut au moins 1 emplacement ; emplacements par défaut'),
'波次为空，使用默认波次': ('No waves found; using default waves', 'Aucune vague ; vagues par défaut'),
'正在使用：{x}': ('Using: {x}', 'Configuration : {x}'),
'正在使用：默认配置': ('Using: default config', 'Configuration : par défaut'),
'正在读取…': ('Reading…', 'Lecture…'),
'导入失败：{x}': ('Import failed: {x}', 'Échec de l’import : {x}'),
'导入配置表 (.xlsx)': ('Import config (.xlsx)', 'Importer la config (.xlsx)'),
'恢复默认': ('Reset to default', 'Rétablir par défaut'),
'在 Excel 或 Google Sheets 中修改配置表后导出为 .xlsx 再导入，游戏会立即按新数值和名称重新开局。导入的配置只保存在这台设备的浏览器里。':
  ('Edit the config sheet in Excel or Google Sheets, export it as .xlsx and import it here. The game restarts right away with the new numbers and names. Imported configs are saved only in this browser.',
   'Modifie la config dans Excel ou Google Sheets, exporte-la en .xlsx puis importe-la ici. La partie redémarre aussitôt avec les nouvelles valeurs et noms. La config importée reste dans ce navigateur.'),
})
T.update({
'蛇形跑道': ('Serpentine', 'Serpentin'),
'1 进 1 出：一条长蛇形跑道，经典布局': ('1 in, 1 out: one long winding track, the classic layout.', '1 entrée, 1 sortie : une longue piste sinueuse, le tracé classique.'),
'双子跑道': ('Twin Tracks', 'Pistes jumelles'),
'2 进 2 出：两条互不相交的跑道，中间一列空位可以同时照顾两边': ('2 in, 2 out: two separate tracks; the middle column of spots can cover both.', '2 entrées, 2 sorties : deux pistes séparées ; la colonne centrale couvre les deux.'),
'分岔路口': ('The Fork', 'La Fourche'),
'1 进 2 出：跑者在路口分成左右两路，入口处是必争之地': ('1 in, 2 out: runners split left and right at the junction, so the entrance is key.', '1 entrée, 2 sorties : les coureurs se séparent au carrefour ; l’entrée est décisive.'),
'汇流跑道': ('Confluence', 'Confluence'),
'2 进 1 出：两路跑者从两侧进场，在中间汇合后一起冲向终点': ('2 in, 1 out: runners enter from both sides, merge in the middle and rush the finish together.', '2 entrées, 1 sortie : les coureurs arrivent des deux côtés, se rejoignent au centre et filent ensemble.'),
'十字路口': ('Crossroads', 'Carrefour'),
'2 进 2 出：一路从上到下、一路从左到右，两条跑道在右下交叉': ('2 in, 2 out: one track runs top to bottom, the other left to right; they cross at the bottom right.', '2 entrées, 2 sorties : une piste du haut vers le bas, l’autre de gauche à droite ; elles se croisent en bas à droite.'),
'三路汇聚': ('Trident', 'Trident'),
'3 进 1 出：左右两路绕远，中路直冲终点，要优先守住中路': ('3 in, 1 out: the side tracks loop around while the middle one runs straight to the finish, so guard the middle first.', '3 entrées, 1 sortie : les côtés font un détour, le centre file droit à l’arrivée ; protège le centre en priorité.'),
'随机': ('Random', 'Aléatoire'),
'跑道选择': ('Track', 'Piste'),
'本局跑道：{x}。{d}': ('Track: {x}. {d}', 'Piste : {x}. {d}'),
'跑道 {x} enabled': ('Track {x} enabled', 'Piste {x} enabled'),
'跑道 {x} spdMult': ('Track {x} spdMult', 'Piste {x} spdMult'),
'跑道 {x} hpMult': ('Track {x} hpMult', 'Piste {x} hpMult'),
'地图：跑道「{x}」不在「跑道列表」里，已忽略': ('Map: track “{x}” is not in the track list; ignored', 'Carte : piste « {x} » absente de la liste ; ignorée'),
'地图「{x}」：每条路线至少需要 2 个点，保留原跑道': ('Map “{x}”: each route needs at least 2 points; kept the previous track', 'Carte « {x} » : chaque tracé demande 2 points ; piste précédente conservée'),
'地图「{x}」：至少需要 1 个空位，保留原空位': ('Map “{x}”: at least 1 spot is needed; kept the previous spots', 'Carte « {x} » : il faut au moins 1 emplacement ; emplacements précédents conservés'),
})
T.update({
'导入美术图片（可多选）': ('Import art images (multiple)', 'Importer des images (plusieurs)'),
'清除导入的图片': ('Clear imported images', 'Effacer les images importées'),
'图片文件名用资源编号命名（如 tower.dart.png、boss.yawn.png），会自动替换对应的占位图。编号和尺寸见配置表「美术资源」工作表。': ('Name each image file after its asset key (e.g. tower.dart.png, boss.yawn.png) and it replaces the matching placeholder. Keys and sizes are in the “美术资源” (Art) sheet of the config workbook.', 'Nommez chaque image d’après sa clé (ex. tower.dart.png, boss.yawn.png) : elle remplace le dessin provisoire correspondant. Clés et tailles : feuille « 美术资源 » (Art) du classeur.'),
'美术资源：全部使用占位图': ('Art: all placeholders', 'Graphismes : tout est provisoire'),
'美术资源：已替换 {n} 项（其中导入 {m} 张）': ('Art: {n} replaced ({m} imported)', 'Graphismes : {n} remplacés ({m} importés)'),
'加载失败：{x}': ('Failed to load: {x}', 'Échec du chargement : {x}'),
'这些文件名不是资源编号，已跳过：{x}': ('Skipped (file name is not an asset key): {x}', 'Ignorés (le nom n’est pas une clé) : {x}'),
'图片太大，浏览器存不下，只在本次打开期间有效': ('Images too large for browser storage; they last only until you close the page', 'Images trop lourdes pour le navigateur : valables jusqu’à la fermeture de la page'),
'美术资源：新编号「{x}」游戏里没有用到': ('Art: key “{x}” is not used by the game', 'Graphismes : la clé « {x} » n’est pas utilisée'),
'美术资源 {x} {k}': ('Art {x} {k}', 'Graphismes {x} {k}'),
})
T.update({
'点击开始': ('Tap to start', 'Touchez pour commencer'),
'点跑道旁的石台放置装置，再点装置直接升级。': ('Tap a stone pad beside the track to place a device, then tap the device to upgrade it.', 'Touchez un socle près de la piste pour poser un dispositif, puis touchez-le pour l’améliorer.'),
'开跑！': ('Go!', 'Partez !'),
'神秘箱开启中…': ('Opening the Mystery Box…', 'Ouverture de la Mystery Box…'),
'准备…': ('Get ready…', 'Prêt…'),
'建造装置': ('Build a device', 'Construire'),
'关闭': ('Close', 'Fermer'),
'已锁定': ('Locked', 'Verrouillé'),
'主': ('Main', 'Princ.'),
'次': ('2nd', 'Sec.'),
'主路线可升满 5 级，次路线最多 2 级': ('Main path up to tier 5, second path up to tier 2', 'Voie principale jusqu’au niv. 5, secondaire jusqu’au niv. 2'),
'回收 +{n}': ('Recycle +{n}', 'Recycler +{n}'),
'跑步加成': ('Running boost', 'Bonus de course'),
'真实跑步会让你的装置更强。原型里用下面的开关模拟；正式版自动读取你在 STEPN 的跑步数据。': ('Real runs make your devices stronger. In this prototype you simulate it with the controls below; the live version reads your STEPN running data automatically.', 'Courir pour de vrai renforce tes dispositifs. Dans ce prototype, simule-le ci-dessous ; la version finale lira automatiquement tes données de course STEPN.'),
'公会天赋（模拟累计 RP）': ('Guild talent (simulated total RP)', 'Talent de guilde (RP cumulés simulés)'),
'累计 {r} RP · 未解锁': ('{r} RP total · locked', '{r} RP cumulés · verrouillé'),
'累计 {r} RP · {t} 档 +{b}%': ('{r} RP total · tier {t} +{b}%', '{r} RP cumulés · palier {t} +{b} %'),
'今日热身：今天在 STEPN 已跑满 {k} km → 当天所有对局装置效果 +{b}%': ('Warm-up: ran at least {k} km in STEPN today → all devices +{b}% effect in every run today', 'Échauffement : au moins {k} km courus dans STEPN aujourd’hui → tous les dispositifs +{b} % d’effet dans chaque partie du jour'),
'天赋怎么提高：每次真实跑步获得 RP（跑步积分）——前 5 km 每 km {a} RP，5–10 km 每 km {b} RP，单日最多 {c} RP。累计 RP 达到 {t1} / {t2} / {t3} 自动解锁一 / 二 / 三档公会天赋，全部装置效果 +{p1}% / +{p2}% / +{p3}%。按每周跑 4 次、每次 4.5 km 计算，大约 1 周、3 周、7 周解锁。': ('How to raise your talent: every real run earns RP (Run Points) — {a} RP per km for the first 5 km, {b} RP per km from 5 to 10 km, up to {c} RP a day. Reaching {t1} / {t2} / {t3} total RP unlocks guild talent tier 1 / 2 / 3: all devices +{p1}% / +{p2}% / +{p3}% effect. Running 4 times a week at 4.5 km each, that takes about 1, 3 and 7 weeks.', 'Comment monter ton talent : chaque vraie course rapporte des RP (points de course) — {a} RP par km sur les 5 premiers km, {b} RP par km de 5 à 10 km, {c} RP max par jour. À {t1} / {t2} / {t3} RP cumulés, tu débloques le palier 1 / 2 / 3 du talent de guilde : tous les dispositifs +{p1} % / +{p2} % / +{p3} % d’effet. En courant 4 fois par semaine 4,5 km, comptez environ 1, 3 et 7 semaines.'),
'当前跑步加成：装置效果 +{n}%': ('Current running boost: devices +{n}%', 'Bonus de course actuel : dispositifs +{n} %'),
'跑步加成 +{n}%': ('Running boost +{n}%', 'Bonus de course +{n} %'),
})
T.update({
'点跑道旁的石台放置装置，再点「开始第 1 波」': ('Tap a stone pad beside the track to place a device, then press “Start wave 1”', 'Touchez un socle près de la piste pour poser un dispositif, puis « Lancer la vague 1 »'),
})
T.update({
'宝石发射器': ('Gem Launcher', 'Lance-gemmes'),
'宝石': ('Gems', 'Gemmes'),
'发射宝石：红宝石主攻暴击，黄宝石主攻连发和 GST，蓝宝石减速冻结': ('Fires gems: ruby for crits, topaz for multi-shot and GST, sapphire to slow and freeze', 'Tire des gemmes : rubis pour les critiques, topaze pour les tirs multiples et le GST, saphir pour ralentir et geler'),
'红宝石': ('Ruby', 'Rubis'), '黄宝石': ('Topaz', 'Topaze'), '蓝宝石': ('Sapphire', 'Saphir'),
'打磨红宝石': ('Polished Ruby', 'Rubis poli'), '效果 +1': ('Effect +1', 'Effet +1'),
'鸽血红': ('Pigeon Blood', 'Sang de pigeon'), '暴击率 +20%': ('Crit chance +20%', 'Critique +20 %'),
'红宝石切面': ('Ruby Facets', 'Facettes de rubis'), '暴击 ×3，对耐力跑者全额生效': ('Crits ×3, full effect on endurance runners', 'Critiques ×3, effet total sur les coureurs endurants'),
'炽红核心': ('Blazing Core', 'Cœur ardent'), '效果 ×2，对 Boss 再 ×1.5': ('Effect ×2, ×1.5 more vs bosses', 'Effet ×2, encore ×1,5 contre les boss'),
'红宝石之心': ('Heart of Ruby', 'Cœur de rubis'), '效果 +12，暴击率再 +20%': ('Effect +12, crit chance +20% more', 'Effet +12, critique encore +20 %'),
'黄晶碎片': ('Topaz Shard', 'Éclat de topaze'), '出手间隔 −15%': ('Interval −15%', 'Intervalle −15 %'),
'双生黄晶': ('Twin Topaz', 'Topaze jumelle'), '每次多打 1 名跑者': ('Hits 1 more runner per shot', 'Touche 1 coureur de plus par tir'),
'黄晶矿脉': ('Topaz Vein', 'Filon de topaze'), '每波结束额外 +40 GST': ('+40 GST at the end of each wave', '+40 GST à la fin de chaque vague'),
'黄晶棱镜': ('Topaz Prism', 'Prisme de topaze'), '再多打 2 名跑者，出手间隔 −25%': ('Hits 2 more runners, interval −25%', 'Touche 2 coureurs de plus, intervalle −25 %'),
'GST 金矿': ('GST Gold Mine', 'Mine d’or GST'), '每波结束再 +120 GST，出手间隔减半': ('+120 GST more per wave, interval halved', '+120 GST de plus par vague, intervalle divisé par deux'),
'冰蓝切片': ('Ice-Blue Slice', 'Tranche bleu glace'), '命中减速 25%，持续 1.5 秒': ('Hits slow by 25% for 1.5 s', 'Ralentit de 25 % pendant 1,5 s'),
'深海蓝': ('Deep-Sea Blue', 'Bleu abyssal'), '射程 +25': ('Range +25', 'Portée +25'),
'蓝宝石冰封': ('Sapphire Freeze', 'Gel de saphir'), '命中时冻住非 Boss 跑者 0.6 秒': ('Hits freeze non-boss runners for 0.6 s', 'Gèle les coureurs (hors boss) 0,6 s'),
'寒光': ('Cold Gleam', 'Éclat glacé'), '被减速的跑者受到所有效果 +30%': ('Slowed runners take +30% from everything', 'Les coureurs ralentis subissent +30 % de tout'),
'星海蓝钻': ('Star-Sea Diamond', 'Diamant mer d’étoiles'), '减速 50%，冻结 1.2 秒，Boss 也吃满减速': ('Slow 50%, freeze 1.2 s, bosses take the full slow', 'Ralentit de 50 %, gèle 1,2 s, les boss subissent tout le ralentissement'),
'解锁宝石发射器：红、黄、蓝三种宝石对应三条路线': ('Unlock the Gem Launcher: ruby, topaz and sapphire are its three paths', 'Débloque le Lance-gemmes : rubis, topaze et saphir sont ses trois voies'),
'额外放置点': ('Extra Spot', 'Emplacement bonus'),
'获得 1 个放置点：点地图上跑道以外的空地，新增一个装置空位': ('Gain 1 spot: tap open ground off the track to add a new device spot', 'Gagne 1 emplacement : touche un terrain libre hors de la piste pour créer un emplacement'),
'下一级：{x}': ('Next: {x}', 'Suivant : {x}'),
'这里不能放': ('Can’t place here', 'Impossible ici'),
'取消放置': ('Cancel placing', 'Annuler'),
'＋ 放置点 ×{n}': ('+ Spot ×{n}', '+ Emplacement ×{n}'),
'点跑道外的空地，新增一个放置点': ('Tap open ground off the track to add a spot', 'Touche un terrain libre hors piste pour ajouter un emplacement'),
})

